notifications:
  email: false

language: cpp

compiler:
 - clang
 - gcc

before_install: ./install-travis-deps.sh

script:
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
 - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
 - . /opt/qt54/bin/qt54-env.sh
 - qmake QMAKE_CC=$CC QMAKE_CXX=$CXX QMAKE_CXXFLAGS+="-g" QMAKE_CFLAGS+="-g"
 - make -j2
 - valgrind ./acquisition --test -platform offscreen
